name: amplify_logger
description: Amplify Logger
version: 0.1.0
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  ansicolor: ^2.0.1
  aws_common: ^0.1.0
  amplify_core: 0.5.0
  logging: ^1.0.2
